title: LitElement Documentation
toc:
  try: 
    title: Try LitElement
    url: /try/
    toc: 
      create:
        title: Create your first custom element
        url: /try/create
      use:
        title: Use your element in a web page
        url: /try/use
      properties:
        title: Declare and use properties
        url: /try/properties
      expressions: 
        title: Add a loop and an “if” statement
        url: /try/expressions
      events:
        title: Add an event handler
        url: /try/events
      style: 
        title: Style your element template
        url: /try/style
  docs:
    title: Documentation
    url: /docs/
    toc: 
      create:
        title: Create a component
        desc: Create a new web component with LitElement. Import and use LitElement components in HTML and JavaScript.
        url: /docs/create
        toc:
          install: 
            title: Add LitElement to an npm project
            url: /docs/create#install
          class:
            title: Extend the LitElement base class
            desc: Create a new class for your web component by extending the LitElement base class.
            url: /docs/create#class
          typescript:
            title: Use TypeScript to create a new class
            desc: Use LitElement TypeScript decorators to create a new class for a LitElement-based component.
            url: /docs/create#typescript
          import: 
            title: Import an element
            desc: Import your own or third-party LitElement components in HTML or JavaScript.
            url: /docs/create#import
      templates: 
        title: Templates
        url: /docs/templates/
        toc: 
          create: 
            title: Create a template
            desc: Define a template and specify where it should render.
            type: task
            url: /docs/templates/create
          expressions:
            title: Use properties and logic
            desc: Use JavaScript expressions to add properties, loops, and conditionals to your templates.
            type: task
            url: /docs/templates/expressions
          databinding:
            title: Bind data to a child element 
            desc: Bind to the text content, properties, attributes, and event handlers of a child element.
            type: task
            url: /docs/templates/databinding
          compose:
            title: Compose and nest templates 
            desc: Compose LitElement templates from other templates. 
            type: task
            url: /docs/templates/compose
          slots:
            title: Render light DOM children
            desc: Use slots to include light DOM children in shadow DOM templates.
            type: task
            url: /docs/templates/slots
          design:
            title: Template design concepts
            desc: Concepts for designing templates that render and update efficiently.
            type: concept
            url: /docs/templates/design
          syntax:
            title: Template syntax
            desc: A quick reference to LitElement template syntax.
            type: reference
            url: /docs/templates/syntax
      properties: 
        title: Properties
        url: /docs/properties
        toc:
          declare: 
            title: Declare properties
            url: /docs/properties#declare
          init: 
            title: Initialize property values
            url: /docs/properties#init
          type:
            title: Configure a property type
            url: /docs/properties#type
          attribute:
            title: Configure observed attributes
            url: /docs/properties#attribute
          reflect:
            title: Configure reflection to attributes
            url: /docs/properties#reflect
          haschanged:
            title: Evaluate property changes
            url: /docs/properties#haschanged
      lifecycle: 
        title: Element update lifecycle
        desc: Specify when an element should update. Respond to updates, or wait for an update to complete.
        url: /docs/lifecycle/
        toc:
          about:
            title: About the element update lifecycle
            desc: Concepts for working with LitElement's asynchronous update lifecycle.
            type: concept
            url: /docs/lifecycle/about
          customize:
            title: Customize lifecycle behavior
            desc: Customize how and when an element should update, and perform additional tasks during any stage of the update lifecycle.
            type: task
            url: /docs/lifecycle/customize
          methods:
            title: Methods and Promises reference
            desc: A reference to the methods and Promises in the LitElement update lifecycle.
            type: reference
            url: /docs/lifecycle/methods
  tools:
    title: Tools
    url: /tools/
    toc: 
      setup:
        title: Set up LitElement locally
        desc: Set up LitElement for the first time.
        url: /tools/setup
      develop:
        title: Develop
        desc: Tools for developing and working locally with LitElement projects.
        url: /tools/develop
      build: 
        title: Build for production
        desc: Get your project ready for deployment to the web.
        url: /tools/build
      sample: 
        title: Sample project
        desc: Clone, serve, and build a sample LitElement project.
        url: /tools/sample
